### ISSUE TITLE
Custom Update Intervals for Data Providers

### ISSUE THREAD

**Issue by nneelix** [acuparse/acuparse#72]
After setup I am noticing intervals on data updates to be bit slow and I would like to use custom intervals for updates.

Since Accuparse uses crontab the theoretical max is 1x/min, however it should be possible to run 4x cron on 15 second delay to get 15 second updates.  I've been playing around with this a bit but it seems the update intervals for the services is the limit.

- WU underground was only updating every 5 minutes, I have switched WU update interval back to Accurite Access to get Rapid Fire updates.

- DB updates are also only posting at 5 minutes intervals is there a way to post every update from crontab to the db?

- CWOP has restrictions on update intervals so the max every 10min is sufficient.

- Not sure about other services max interval updates.

Thanks,
Arin

**Comment by maxwellpower** [comment]
The Access device only sends updates every 5 mins. This is a limitation of the Access and not Acuparse. Otherwise, I see no value in providing readings at an interval of less than 1 min. If you do want WU rapid fire, then what you did is the only solution at this time. The WU update from the Access does not send tower data and is useless for Acuparse. I suggest you lobby Acurite to allow us to modify the rate at which data is sent from the Access.
